import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Sprint 4 W2-2a — user_invitations table backing the team invitation
 * flow (`POST /users/invitations`, `GET /users/invitations`,
 * `POST /users/invitations/:id/revoke`, public `GET /users/invitations/lookup`
 * + `POST /users/invitations/accept`).
 *
 * State machine (all timestamps optional, mutually exclusive):
 *   - pending   → accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
 *   - accepted  → accepted_at IS NOT NULL (accepted_user_id MUST be populated)
 *   - revoked   → revoked_at  IS NOT NULL
 *   - expired   → expires_at <= now() AND accepted_at IS NULL AND revoked_at IS NULL
 *
 * Token is a 32-byte hex (64 chars) generated by
 * `crypto.randomBytes(32).toString('hex')` in the application layer. The
 * UNIQUE constraint on `token` defends against collision; the partial
 * unique index on `(organization_id, lower(email))` prevents shipping
 * multiple live invites to the same recipient within one org.
 *
 * FK semantics:
 *   - organization_id → organizations ON DELETE CASCADE: when the tenant
 *     is purged (Art. 17), the pending invites go too.
 *   - invited_by_user_id → users ON DELETE SET NULL: keep the invite
 *     audit trail if the inviter is later deleted.
 *   - accepted_user_id  → users ON DELETE SET NULL: same rationale.
 *
 * Reversible — down() drops the table, then the table is gone.
 */
export class UserInvitations1700000045000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Guard: depends on `users` + `organizations` (M1).
    const hasUsers = await queryRunner.hasTable('users');
    const hasOrgs = await queryRunner.hasTable('organizations');
    if (!hasUsers || !hasOrgs) {
      return;
    }

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "user_invitations" (
        "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        "organization_id" uuid NOT NULL,
        "email" varchar(254) NOT NULL,
        "role" varchar(16) NOT NULL,
        "token" varchar(64) NOT NULL,
        "invited_by_user_id" uuid NOT NULL,
        "expires_at" timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
        "accepted_at" timestamptz NULL,
        "accepted_user_id" uuid NULL,
        "revoked_at" timestamptz NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "fk_user_invitations_organization"
          FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON DELETE CASCADE,
        CONSTRAINT "fk_user_invitations_invited_by"
          FOREIGN KEY ("invited_by_user_id") REFERENCES "users" ("id") ON DELETE SET NULL,
        CONSTRAINT "fk_user_invitations_accepted_user"
          FOREIGN KEY ("accepted_user_id") REFERENCES "users" ("id") ON DELETE SET NULL,
        CONSTRAINT "ck_user_invitations_role"
          CHECK ("role" IN ('OWNER', 'MANAGER', 'STAFF'))
      );
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_invitations_token"
        ON "user_invitations" ("token");
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "ix_user_invitations_org_email"
        ON "user_invitations" ("organization_id", "email");
    `);

    // Partial unique: one live invite per (org, normalised email) at a time.
    // "Live" = neither accepted nor revoked. Expired invites still occupy
    // the slot so an Owner can't ship a second invite while one is in
    // limbo — they must revoke first.
    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_invitations_live_org_email"
        ON "user_invitations" ("organization_id", lower("email"))
        WHERE "accepted_at" IS NULL AND "revoked_at" IS NULL;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const exists = await queryRunner.hasTable('user_invitations');
    if (!exists) {
      return;
    }
    await queryRunner.query(`DROP INDEX IF EXISTS "uq_user_invitations_live_org_email";`);
    await queryRunner.query(`DROP INDEX IF EXISTS "ix_user_invitations_org_email";`);
    await queryRunner.query(`DROP INDEX IF EXISTS "uq_user_invitations_token";`);
    await queryRunner.query(`DROP TABLE IF EXISTS "user_invitations";`);
  }
}
